
GET http://localhost:8080/api/posts

###

POST http://localhost:8080/api/posts
Content-Type: application/json

{
  "content": "the Post"
}

###

POST http://localhost:8080/api/posts
Content-Type: application/json

{
  "id": 31,
  "content": "the Post"
}

###

DELETE http://localhost:8080/api/posts/31

